module.exports = {
  projects: [
    '<rootDir>/apps/eam-js',
    '<rootDir>/apps/api',
    '<rootDir>/libs/projects/feature-shell',
    '<rootDir>/libs/projects/api',
    '<rootDir>/libs/components',
    '<rootDir>/libs/projects/data-access',
    '<rootDir>/libs/projects/ui',
    '<rootDir>/libs/utilities',
    '<rootDir>/libs/core',
    '<rootDir>/libs/users/ui',
    '<rootDir>/libs/users/feature-shell',
    '<rootDir>/libs/auth/feature-shell',
    '<rootDir>/libs/dashboard/feature-shell',
    '<rootDir>/libs/settings/feature-shell',
    '<rootDir>/libs/auth/api',
    '<rootDir>/libs/auth/data-access',
    '<rootDir>/libs/auth/ui',
    '<rootDir>/libs/users/api',
  ],
};
